### ISSUE TITLE
Support `\u2630`

### ISSUE THREAD

**Issue by ifreund** [slavfox/Cozette#1]
`\u2630` is the classic "three bars" symbol used for hamburger menus and other things. It also happens to be one of the default symbols used by [vim-airline](https://github.com/vim-airline/vim-airline).  It'd be great if you could add support for it!

The fallback it uses on my system looks blurry and ugly alongside the crisp cleanness of cozette:
![image](https://user-images.githubusercontent.com/12723818/74525486-7db8ce80-4f21-11ea-9623-a42da6460ae8.png)

I'm using `\ue612` instead now, but it seems like `\u2630` is fairly common and would be good to support.

Thanks

**Comment by slavfox** [comment]
Am nowhere near my pc at the moment, but this is definitely near the top of the priority list. I'm using Airline myself, so I'm probably going to just scan the repo for all the codepoints it uses and add those in the next update.

**Comment by slavfox** [comment]
Closed with [v.1.4.0](https://github.com/slavfox/Cozette/blob/master/CHANGELOG.md#140---the-vim-airline-update---2020-02-15)
