### ISSUE TITLE
Not working with Luke Smith build of the st

### ISSUE THREAD

**Issue by l33k685** [slavfox/Cozette#10]
When I want to have this font in st it is not working

**Comment by slavfox** [comment]
It works for me with `.font: Cozette:pixelsize=13` in `.Xresources`. Could you elaborate on "not working"? How do you specify the font? Which format did you download?

**Comment by slavfox** [comment]
Since it's been a week with no response, I'm closing this. Feel free to reopen if the problem persists and you can provide any details that would let me help.

**Comment by Barbarossa93** [comment]
I was having a similar problem when using cozette as a fallback font either with the font2 patch or as part of an alias in fontconfig. Turns out using the ttf version of cozette worked at certain sizes while the otb version didn't work right no matter the size
