### ISSUE TITLE
request: 😎 glyph

### ISSUE THREAD

**Issue by k4y4k** [slavfox/Cozette#101]
hello!

im not sure how to contribute to this repo but im missing possibly **THE** most important emoji out of them all (ok maybe not really THE most 😆): the sunglasses emoji

# 😎

my usecase: i use it in my prompt for git branches that are up to date (i.e. not ahead, not behind) like so 
![image](https://github.com/slavfox/Cozette/assets/41324271/12939887-94fe-457e-90a5-d5577a70beb6)

as you can see, im falling back to wherever the windows 10 moji comes from and it looks not great, esp. next to the Node.js logo.

i feel a bit awkward asking for it, but the readme does mention filing issues to ask for glyphs is OK

**Comment by slavfox** [comment]
Done in [1.20.1](https://github.com/slavfox/Cozette/releases/tag/v.1.20.1)
