### ISSUE TITLE
⟜ (U+27DC) is aligned to the left instead of the right.

### ISSUE THREAD

**Issue by dariof4** [slavfox/Cozette#105]
⟜ (U+27DC) is aligned to the left rather than to the right like most glyphs, this gives it an unsymmetrical look when combined with other characters due to having 3 pixels of whitespace to left and only 1 to the right, in my opinion it would look better it it was aligned to the right.

Here's a comparison with other arrow-like glyphs:
![ex-export](https://github.com/slavfox/Cozette/assets/9992814/6991d94e-dcd1-42af-afaf-cd6261fd97a8)

By the way, awesome job on the 𝕩 and 𝕏 glyphs, getting them to fit such a small pixel size is hard, but they turned out really nice!

**Comment by slavfox** [comment]
I tried to have ⟜ and ⊸ be the same width and align them on the connecting line (with the circle extending the line either left or right), but I can see now that wasn't the right decision. I'll get a little fix pushed soon.

**Comment by slavfox** [comment]
Fixed in [1.22.0](https://github.com/slavfox/Cozette/releases/tag/v.1.22.0).
