### ISSUE TITLE
bold style spacing

### ISSUE THREAD

**Issue by NilTPL** [slavfox/Cozette#108]
Hi - is it possible to change the spacing between each letter but only when cozette is in bold? i adore how the font looks but in bold it's slightly too squished. how do i deal with this?
Im running arch linux

**Comment by slavfox** [comment]
Bitmap fonts don't support separate bold variants, flexible metrics, or anything else that would help with this. If it's a dealbreaker, you probably don't want to use a bitmap font in the first place.
