### ISSUE TITLE
Underline is not displayed correctly

### ISSUE THREAD

**Issue by jeremija** [slavfox/Cozette#11]
I am using [zprezto](https://github.com/sorin-ionescu/prezto) on macOS Catalina and the underline is not displayed correctly with this font.

It looks like:

![image](https://user-images.githubusercontent.com/1489493/76708422-f49ae000-66f6-11ea-810e-6bf114183581.png)

I expect to see (using Monaco 9 without anti-aliasing):

![image](https://user-images.githubusercontent.com/1489493/76708433-0a100a00-66f7-11ea-80e0-8f4e2dc02047.png)

**Comment by slavfox** [comment]
Which terminal and which format of the font are you using? Underline works fine for me on iTerm.

**Comment by jeremija** [comment]
I've tried it with stock Terminal.app and Alacritty. Will check iTerm, but I suspect it will look the same.

**Comment by slavfox** [comment]
Could you try CozetteVector? I have a retina Macbook Air, and the bitmap version looks terrible on that screen, so I haven't exactly tested it there.

**Comment by jeremija** [comment]
Sure, I'll try it out when I'm back at my pc.

**Comment by jeremija** [comment]
Looks normal when using the vector font.

**Comment by slavfox** [comment]
Could you check if [https://github.com/romeovs/creep/releases](Creep) renders the underline okay?

If not, and if the vector font looks okay, I'm probably going to write this off as a MacOS bitmap font quirk and recommend Mac users to use the vector fonts.

**Comment by jeremija** [comment]
Seems to work ok:

![image](https://user-images.githubusercontent.com/1489493/76710566-dd64ee00-6708-11ea-8332-c9da1acd1909.png)

**Comment by slavfox** [comment]
Okay, that's promising! Cozette has what is possibly the most overengineered build process of all the bitmap fonts on Github, but it's still based around Creep - if Creep works fine, this should just be a matter of seeing what's different between the metadata of the two fonts, and fixing it. I'll try and fix it tomorrow.

**Comment by jeremija** [comment]
Thank you :)

**Comment by slavfox** [comment]
I'm not near my Mac ATM, so I can't verify if it works, but here's a version with some changes that I suspect might fix the problem. Will try it later today.
[CozetteDfont.zip](https://github.com/slavfox/Cozette/files/4337074/CozetteDfont.zip)

**Comment by jeremija** [comment]
Yay, looks good now:

Non-retina:

![image](https://user-images.githubusercontent.com/1489493/76738371-c9ea6f00-676a-11ea-8328-c36db04b4d5e.png)

Retina:

<img alt="image" src="https://user-images.githubusercontent.com/1489493/76738393-d2db4080-676a-11ea-995a-09d152027fa0.png">

Thanks!

**Comment by slavfox** [comment]
That's tremendous news! I'll push an update immediately.

**Comment by slavfox** [comment]
The fixed version just got built, and [v.1.6.2](https://github.com/slavfox/Cozette/releases/tag/v.1.6.2) is out. I'll close this issue after I get the chance to verify everything works on my own Mac.

Thank you for reporting this! :tada:

**Comment by jeremija** [comment]
Great, thanks so much for fixing this so quickly! 🍻

**Comment by slavfox** [comment]
PSA for anyone reading this: the fix broke the automated Mac font builds for some reason; they work fine if generated manually through the FontForge UI, but the automated releases are broken for now. The build I posted above ( https://github.com/slavfox/Cozette/issues/11#issuecomment-599411483 ) was built manually from the UI, and so works correctly.

**Comment by slavfox** [comment]
Brought up the issue in https://github.com/fontforge/fontforge/issues/4224 for now.

**Comment by slavfox** [comment]
Just fixed this, and the latest v.1.6.3 release works on my Macbook, so I'm closing the issue.
