### ISSUE TITLE
Uiua glyph support

### ISSUE THREAD

**Issue by JobLeonard** [slavfox/Cozette#113]
Uiua is a new and really cool stack-based array programming language, and like almost all array languages it uses a lot of funny glyphs:

https://www.uiua.org/

Cozette actually appears to support the majority of them already! But there are still quite a few missing. Based on where my LibreOffice Writer applies font substitution to the CozetteVector font, these glyphs do not appear to exist yet:

- ⇵ restack
- ⌵ absolute value
- ◿ modulus
- ⧻ length
- △ shape
- ⊛ classify
- ≅ match
- ↯ reshape
- ◫ windows
- ▽ keep
- ⌕ find
- ⊗ indexof 
- ∵ each
- ⊠ cross
- ⍚ level
- ⎋ break
- ⍜ under
- ∷ both
- ⊜ partition

I realize that that's a lot of glyphs, so I also get that this might not feel directly appealing. On the other hand, being the first bitmap font to support Uiua would be kinda cool no?

**Comment by JobLeonard** [comment]
Indirectly in https://www.uiua.org/docs, but maybe @kaikalii could provide one

**Comment by JobLeonard** [comment]
Also, wow, that's a fast response!

**Comment by kaikalii** [comment]
The majority of glyphs are stable, but not all of them.
Would you like the list of stable glyphs?
Or would you like to hold off until every one of them is nailed down?

**Comment by slavfox** [comment]
I'll take whatever's ready! Cozette's goal is to cover any and all codepoints that might show up in a terminal, so if any get added later I'll just add them as well, and if any get removed... that's still a net gain for the font :D

**Comment by kaikalii** [comment]
Sure thing
```
·→¬±⌵√○⌊⌈⁅≤≥×◿ⁿₙ↧↥∠⧻△⇡⊢⇌♭⋯⍉⌂⊛⊝□⊂⊟≅⊡⊏↯↙↘↻◫▽⌕∊⊗∧∵≡∺⊞⊠⍥⊕⊜⍘⍜⍛⍚∷⊃∋∝⍣⍤↰↲!⎋↬⚂
```
The only one's I've left out are the ASCII ones and some greek letters and infinity, since you probably have those.
