### ISSUE TITLE
nerdfont glyph request: f417 nf-oct-git_commit

### ISSUE THREAD

**Issue by apaleslimghost** [slavfox/Cozette#115]
![Screenshot 2023-11-06 at 11 40 21](https://github.com/slavfox/Cozette/assets/631757/8722267d-d860-406a-9ca9-996f62db6718)

it's used when you're on a detached git head by the oh-my-posh theme i use

**Comment by slavfox** [comment]
Added in [v.1.23.0](https://github.com/slavfox/Cozette/releases/tag/v.1.23.0)
