### ISSUE TITLE
Weird pixel artifact when printing "😊" Unicode: U+1F60A

### ISSUE THREAD

**Issue by erf** [slavfox/Cozette#117]
😊
smiling face with smiling eyes
Unicode: U+1F60A, UTF-8: F0 9F 98 8A

Output the following with a few initial newlines:
```


😊😊😊😊
```

<img width="172" alt="Screenshot 2023-11-16 at 09 40 49" src="https://github.com/slavfox/Cozette/assets/1562523/6a59c1e6-33aa-4a8e-9387-7495286788ae">

on macOS, version 1.23.0

**Comment by slavfox** [comment]
Fixed in [v.1.23.1](https://github.com/slavfox/Cozette/releases/tag/v.1.23.1)
