### ISSUE TITLE
Braille U+2800 blank character not provided, breaks ascii art

### ISSUE THREAD

**Issue by kidofcubes** [slavfox/Cozette#125]
![image](https://github.com/slavfox/Cozette/assets/40485669/47ac9c2f-ef5c-4123-94eb-d7677ea95d97)
![image](https://github.com/slavfox/Cozette/assets/40485669/fadab095-6f0a-4993-8322-6e24f5ba930d)

appears in CozetteVector

**Comment by slavfox** [comment]
Fixed in [1.24.1](https://github.com/slavfox/Cozette/releases/tag/v.1.24.1)
