### ISSUE TITLE
please add ruble sign

### ISSUE THREAD

**Issue by swex** [slavfox/Cozette#13]
Hello!
Thank you for great work! Can you please add ruble character!?
https://en.wikipedia.org/wiki/Ruble_sign

**Comment by slavfox** [comment]
Just pushed a new release with it:
https://github.com/slavfox/Cozette/releases/tag/v.1.7.1

**Comment by slavfox** [comment]
I accidentally screwed up the release. [v.1.7.2](https://github.com/slavfox/Cozette/releases/tag/v.1.7.2) *actually* has the ruble sign.

I'll close this as soon as the AUR packages get updated.

**Comment by ifreund** [comment]
@slavfox just bumped them!

**Comment by slavfox** [comment]
Awesome, thanks!
