### ISSUE TITLE
Contribution: Double-Spaced Japanese Characters!

### ISSUE THREAD

**Issue by bluetoad07** [slavfox/Cozette#130]
Hi! I want to start by thanking you for this amazing font. I love it and use it for basically everything.

However, I do wish it had Japanese characters, so I made them!

![cozette-kana-example](https://github.com/user-attachments/assets/bb98c66c-d679-4cb1-8a88-d0da907c63bb)
<sup>Translates to _hiragana & katakana_</sup>

This includes hiragana and katakana, the main 2 Japanese alphabets (collectively referred to as _kana,_) native Japanese punctuation, and full-width Roman characters, which are used frequently in Japanese text.

All the characters are arranged in a grid on a transparent Unicode map png. I would put them into the proper file format for this sort of thing, but I don't know what that would be or how I would do that. That said, if using an image is inconvenient and there is a way I can make this easier to work with for you, please let me know!

Here is the raw Unicode map:

![cozette-kana-map](https://github.com/user-attachments/assets/806a9237-bd20-4fd1-9469-ba188e22af84)

. . . and an upscaled version with a background that's easier to see here:

![cozette-kana-map-big](https://github.com/user-attachments/assets/da57ba58-f716-41fa-9afc-3d7281da9d9e)

### Notes on how I formatted the file:

These are all designed to fit within a bounding box twice the size of regular Cozette characters (12:13). I'm not exactly sure how double-spaced characters in monospaced fonts work, but I've seen it done before in fonts like _Noto Sans Mono CJK JP_ (my current fallback font for Japanese characters.)

- Red Xs mean that the charecters have not been included in my set or do not exist.

- Generally speaking, the kana are 9x9 pixels and are positioned 3 pixels from bottom, 2 pixels from left, and 1 pixel from top and right. Some characters (and basically anything with a dakuten/handakuten) exceed or preceed this box, but nothing ever passes below the bottom or top padding, as well as the leftmost column (examples below.)

![cozette-kana-size](https://github.com/user-attachments/assets/7225dae5-7e8b-4298-8e07-e043b0f888f1)

- Any empty space within the 12x13 gridspace for a character is intentional and **should** be included in the character. If it isn't then things get squished :( 

- Japanese exclusive brackets and quotes are moved up by one pixel, making them centered to the kana characters. 

- Full-width Roman characters are copied from the  original font and centered within the wider box. I modified some of the punctuation to look more natural.

**Everything in the file is aligned properly to a 12x13 grid, so hopefully you shouldn't have to worry about positioning anything.**

#### Character-Specific Notes:

- U+3000 is a double-width space. It is blank on purpose.

- U+303c is an actual character called the masu mark. It kind of looks like a missing character symbol or something like that, so I just wanted to clarify that it's not a mistake.

- U+3040 is an unassigned space in Unicode. I put my watermark there :) You don't have to include it if you don't want to.

Again, if I can put this picture into a different format or layout that would make it easier to work with, please let me know!

Thank you <3

**Comment by slavfox** [comment]
This is wonderful! Thank you, I'll take a look at this as soon as I have some time <3

**Comment by slavfox** [comment]
![image](https://github.com/user-attachments/assets/e3153ff0-4e17-4f5a-afad-0309f017c2e1)

Released in [v.1.25.0](https://github.com/slavfox/Cozette/releases/tag/v.1.25.0)!

**Comment by bluetoad07** [comment]
Yay! Thank you so much!
