### ISSUE TITLE
U+0306f is an accidental duplicate of U+0307b

### ISSUE THREAD

**Issue by bluetoad07** [slavfox/Cozette#131]
Thank you very much for adding my characters! Unfortunately I think I overlooked something. 
Hiragana character は was accidentally listed as ほ and is a duplicate in the font. All of its alts (ば, ぱ) are correct though. Here's the correct one:
![hiragana-ha](https://github.com/user-attachments/assets/0434bbec-29e9-4d7b-a88e-063724ec1fe1)
Also, if you could replace U+030df (ミ) with this version while you're at it, that would be great.
![katakana-mi](https://github.com/user-attachments/assets/741e720c-4531-4e69-b307-6a214a25a82e)
Thank you, very sorry about this.

**Comment by slavfox** [comment]
Fixed in [1.25.1](https://github.com/slavfox/Cozette/releases/tag/v.1.25.1)!
