### ISSUE TITLE
Hiragana せ and ぜ have wrong glyphs

### ISSUE THREAD

**Issue by sungodmoth** [slavfox/Cozette#132]
U+305B HIRAGANA LETTER SE mistakenly looks like U+304D HIRAGANA LETTER KI, and U+305C HIRAGANA LETTER ZE looks like U+304E HIRAGANA LETTER GI. Noticed this while looking at the iroha pangram in `sample.png`, and confirmed in the source file. I would have submitted a PR, but fixing this necessitates a new design and I'm not sure mine would match the preexisting kana set.

**Comment by bluetoad07** [comment]
Yep. I can't believe I missed this when I double checked everything. Here's the designs: 
![hiragana-se-ze](https://github.com/user-attachments/assets/f852ecd2-886c-41e8-a833-2a1d5003b319)
Thanks for pointing this out!

**Comment by slavfox** [comment]
I have this implemented, but ran into some build problems after migrating my workstation to a new machine. This will get released with the next update, as soon as I have time to debug it more thoroughly.

**Comment by slavfox** [comment]
Released in 1.25.2! Sorry for the delay.
