### ISSUE TITLE
icons missing

### ISSUE THREAD

**Issue by Anyell0w** [slavfox/Cozette#133]
usual nerd font icons like copilot or other file types are missing this problem occurs even outside nvim in windows terminal
![image](https://github.com/user-attachments/assets/c113e397-fbfc-4de1-984a-86f72a27b786)
![image](https://github.com/user-attachments/assets/9bc69b3e-4037-4ca9-8fa7-4eb04b5ac6e8)
![image](https://github.com/user-attachments/assets/1a07423f-da0a-4370-9e28-e7ba4bf2f8e0)

I don't know if I missed a step or if there is a solution.

thanks in advance.

**Comment by slavfox** [comment]
If you would like more glyphs added to the font, please provide me with a list of codepoints or a link to the repo for the plugin you're using that provides them and I'll get on it for the next release.

**Comment by Anyell0w** [comment]
Sorry, my english is so bad and and I have a hard time thinking what you mean, I think what you need would be this link, right? 
https://github.com/ryanoasis/nerd-fonts 
It has quite a few glyphs and even a search engine for them: https://www.nerdfonts.com/cheat-sheet
If you need more information, let me know. THANKSSS

**Comment by slavfox** [comment]
Cozette implements nerdfonts glyphs, I know what nerdfonts is. I need a list of codepoints, i.e. characters, that you would like implemented. You can provide me either a list, or a link to the repository for the vim plugin you are using that provides the icons.

**Comment by Anyell0w** [comment]
I understand, you're talking about these codepoints, right?
![image](https://github.com/user-attachments/assets/8f1dc313-1927-486f-812a-6d58634a2460)

**Comment by slavfox** [comment]
This would be one of them, yes. Either the name (`nf-cod-file_binary`), character (``), codepoint (`eae8`), or a link to the repo for the vim plugin you are using that provides the icons would give me sufficient information to add them to the font.

**Comment by Anyell0w** [comment]
https://github.com/simrat39/symbols-outline.nvim | Since I'm currently using lazyvim with some default plugins and configurations, I assume this repo is the one that provides the icons.
