### ISSUE TITLE
Submit Cozette to Google Fonts

### ISSUE THREAD

**Issue by robinplace** [slavfox/Cozette#134]
I've been a happy user of Cozette for a handful of years now. I'd love to be able to use my favorite font in spreadsheets and other documents in Google Drive.

While there are a few steps to complete to include a font, as far as I understand the hard parts are complete:
- Cozette is already under an SIL compatible license, MIT.
- Cozette has very high glyph coverage. I'm not 100% sure all the required ["latin core" glyphs](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt) are covered, but there's surely not many missing.

I'd be happy to work with the Google Fonts maintainers on the submission process. @slavfox would you support `CozetteVector` being added to the Google Fonts library?

**Comment by slavfox** [comment]
I am very firmly against adding Cozette to Google Fonts. Please do not add Cozette to Google Fonts. The Vector version looks horrible, implementing it at all was a mistake, it is effectively unsupported, and Google Fonts is one of the most prolific spyware on the Internet. Please do not add Cozette to Google Fonts.
