### ISSUE TITLE
Should Cozette HiDPI have a family name of "Cozette"?

### ISSUE THREAD

**Issue by remexre** [slavfox/Cozette#138]
I have two monitors, one HiDPI and one not. Alacritty on Wayland with Terminus is able to adapt between them, using a larger font size on the HiDPI monitor to compensate for the smaller pixel size. This doesn't seem to work with Cozette 1.24.1 as shipped in the GitHub releases, because Cozette HiDPI has a different family name than the normal version.

I'm using this Python script to patch the font and fix this, but is there any reason not to just generate it in the first place with the same family name, since they are the same family?

```python
font = fontforge.open(sys.argv[1])
font.familyname = "Cozette"
font.generate(sys.argv[1])
```

**Comment by im-n1** [comment]
I do upvote for this. I have to switch between hi-dpi and non-hi-dpi version in many programs.

**Comment by slavfox** [comment]
Fixed in [v.1.6.0](https://github.com/slavfox/Cozette/releases/tag/v.1.26.0)
