### ISSUE TITLE
Pomicons

### ISSUE THREAD

**Issue by liquid600pgm** [slavfox/Cozette#15]
This is a request to add [Pomicons](https://github.com/gabrielelana/pomicons). These are icons for Pomodoro timers, and unfortunately Cozette doesn't have them yet.

**Comment by slavfox** [comment]
Will do this week.

**Comment by slavfox** [comment]
Released in [1.8.0](https://github.com/slavfox/Cozette/releases/tag/v.1.8.0). Please try it out and let me know if they look fine.

**Comment by liquid600pgm** [comment]
They're very nice, thank you.
