### ISSUE TITLE
Mixed up glyphs for ▼▲ codepoints

### ISSUE THREAD

**Issue by bbrks** [slavfox/Cozette#19]
- `U+25B2` (▲) shows a down-pointing triangle, instead of up-pointing
- `U+25BC` (▼) shows an up-pointing triangle, instead of down-pointing

![Screenshot_2020-05-28_13-39-26](https://user-images.githubusercontent.com/1525809/83142656-b5224400-a0e8-11ea-878a-d67e20e46bbb.png)
![Screenshot_2020-05-28_13-39-34](https://user-images.githubusercontent.com/1525809/83142658-b5bada80-a0e8-11ea-98a6-a37309c629f2.png)

**Comment by bbrks** [comment]
Going to open a PR for this in a minute :+1:

**Comment by slavfox** [comment]
I just pushed a fix :sweat_smile:

**Comment by bbrks** [comment]
No problem! You're too fast for me :laughing:

**Comment by slavfox** [comment]
Fixed in [v.1.8.2](https://github.com/slavfox/Cozette/releases/tag/v.1.8.2) - thanks for catching it!

**Comment by bbrks** [comment]
It will make my ASCII code comments less confusing now :rofl:
