### ISSUE TITLE
Cutoff charmap.png after ef28014

### ISSUE THREAD

**Issue by TheAvidDev** [slavfox/Cozette#21]
After commit [`ef28014`](https://github.com/slavfox/Cozette/commit/ef28014084ee25ca37b5b37a7d3d4cd74d7db3d0), the [`charmap.png`](https://github.com/slavfox/Cozette/blob/ef28014084ee25ca37b5b37a7d3d4cd74d7db3d0/img/charmap.png) has white space at the top, only starting at `U+016A_`.

**Comment by slavfox** [comment]
I'm actually in the middle of fixing it right now :D Good timing.

**Comment by slavfox** [comment]
[Fixed!](https://github.com/slavfox/Cozette/blob/master/img/charmap.png)
