### ISSUE TITLE
macOS Weird Rendering

### ISSUE THREAD

**Issue by tsujp** [slavfox/Cozette#26]
Howdy, love Cozette use it on my Linux distro of choice 24/7. Want to use it on macOS but it appears as the following no matter where it's used (Sublime, Browser, TextEdit etc). Does Cozette work as expected for others on macOS or are there any known workarounds I can try?

![image](https://media.discordapp.net/attachments/280102180189634562/738651579376205884/Screen_Shot_2020-07-31_at_2.57.28_pm.png)

**Comment by slavfox** [comment]
Hi, can you confirm your exact Mac model/dpi/resolution, the software you're using, font size (should be 13 points on MacOS iirc), and font rendering settings? It would help a lot in tracking down the issue.

**Comment by tsujp** [comment]
I am using Sublime Text 4 dev build 4079 (same as what I use on Linux with no problems). Just set the font size to 13 then and it looks much, much better but still noticeably broken or weird looking.

The machine is a Macbook Pro (15-inch 2017), model name is `MacBookPro14,3`. Running `macOS Catalina 10.15.6`. This is as shown on the laptop screen not an external one.

This is what it looks like in Font Book zoomed in at size 49, and again following at size 13.

![size49](https://i.imgur.com/VDN2Wdo.png)
1[sizs13](https://i.imgur.com/KtmcQYq.png)

This is using the `.dfont` variant from the latest release, `v.1.8.3`.

**Comment by tsujp** [comment]
Attempting to install the `.ttf` results in this error and nothing been shown at all:

![image](https://i.imgur.com/W9g3WvJ.png)

**Comment by tsujp** [comment]
Finally for completeness here is Linux (note that the italic also works here, unsure how or why but it does):

![linux](https://i.imgur.com/p4gyDWk.png)

**Comment by tsujp** [comment]
@slavfox huge info dump but wanted to be comprehensive :)

**Comment by slavfox** [comment]
Looks like Sublime's using a weird algorithm for rendering italics; there's not much I can do about that, unfortunately. Non-Linux OSes are notoriously unfriendly towards bitmap fonts, _especially_ on the machines with Retina screens  - can you try using CozetteVector and playing around with the point size?

FWIW, the screenshot from Font Book looks to be about the same as what I'm seeing on my Macbook, so I'm afraid this might be as good as you can get :(

**Comment by tsujp** [comment]
Bugger. Unfortunately on both machines CozetteVector is blurry (well, all non-bitmap fonts are; I yearn for that pixel-precision). It's okay, thanks for the effort. I might just have to continue trying to get Linux working so I don't have to use macOS. My addiction for Cozette is too high!
