### ISSUE TITLE
Two missing glyphs in Baltic script

### ISSUE THREAD

**Issue by elitepleb** [slavfox/Cozette#27]
Ų, U+0172 LATIN CAPITAL LETTER U WITH OGONEK
ų, U+0173 LATIN SMALL LETTER U WITH OGONEK

Missing these two has been bugging me, as every other baltic letter is covered already.

**Comment by slavfox** [comment]
I've added the glyphs, but I'm having issues with the build scripts locally. I'll try and push a new version tomorrow.

**Comment by slavfox** [comment]
Done in [v.1.9.0](https://github.com/slavfox/Cozette/releases/tag/v.1.9.0).
