### ISSUE TITLE
CozetteVector.TTF does not work with Microsoft Word and WordPad

### ISSUE THREAD

**Issue by eggjoystick** [slavfox/Cozette#30]
![cozette-vector-word-issue](https://user-images.githubusercontent.com/58571795/91727930-028ad300-eb68-11ea-8bce-6791c9a92e05.png)

When trying to use Cozette Vector in Microsoft Word 2016, the font displayed seems to be the same as Courier New. WordPad is also unable to use the font correctly. The dropdown preview of fonts shown in Word also displays Cozette in the style of Courier New.

However, Notepad and LibreOffice Witer are both able to display the Cozette Vector correctly. A freeware screenshotting program called Greenshot is also able to use it correctly.

**Comment by jmkeol** [comment]
I'm getting the same result.

For some reason the font works with Microsoft PowerPoint, but not Word/WordPad. This might be an issue to do with Word/WordPad.

**Comment by eggjoystick** [comment]
I agree that this issue is a result of something very specific to Word and WordPad. It'd be great though for the TTF to work well with those programs though just because of how widespread they are.

**Comment by slavfox** [comment]
![image](https://github.com/slavfox/Cozette/assets/35173529/37c9dc07-fc0a-46eb-826a-96833bfb432e)

Three years later and purely by accident, but this should now work.
