### ISSUE TITLE
U+04CC CYRILLIC SMALL LETTER KHAKASSIAN CHE has a short descender

### ISSUE THREAD

**Issue by dscorbett** [slavfox/Cozette#33]
In version 1.9.2, the descender of U+04CC CYRILLIC SMALL LETTER KHAKASSIAN CHE is shorter than those of other characters with descenders like U+04B7 CYRILLIC SMALL LETTER CHE WITH DESCENDER and U+04CB CYRILLIC CAPITAL LETTER KHAKASSIAN CHE.

**Comment by slavfox** [comment]
Fixed in [v.1.9.3](https://github.com/slavfox/Cozette/releases/tag/v.1.9.3)
