### ISSUE TITLE
U+220F N-ARY PRODUCT and U+2210 N-ARY COPRODUCT are too short

### ISSUE THREAD

**Issue by dscorbett** [slavfox/Cozette#34]
U+220F N-ARY PRODUCT and U+2210 N-ARY COPRODUCT are too short. They should, as <var>n</var>-ary operators, be taller than caps-height, like the current glyph for U+2225, but their glyphs are x-height. Here they are with U+03C0 GREEK SMALL LETTER PI for comparison.
![∏∐π](https://user-images.githubusercontent.com/1124347/95281396-0e337e80-0825-11eb-81f2-95bbed0c2a5d.png)

**Comment by slavfox** [comment]
Fixed in [v.1.9.3](https://github.com/slavfox/Cozette/releases/tag/v.1.9.3)
