### ISSUE TITLE
CozetteVector >1.8.0 not working on Windows

### ISSUE THREAD

**Issue by musjj** [slavfox/Cozette#35]
CozetteVector stopped working for Windows after version 1.8.0.
Opening the ttf file using the default Windows Font Viewer shows nothing, as if it is corrupted.
Here's screenshot comparing version 1.8.0 (the front window) vs. >1.8.0 (the back window):
![image](https://user-images.githubusercontent.com/72612857/96740277-e0386780-13ea-11eb-9cc1-dea42e1ba80c.png)

**Comment by slavfox** [comment]
Is this still the case? Folks in some other issues seem to be able to use it on Windows.

**Comment by slavfox** [comment]
1.19.2-hidpi verified working on Win11, closing.
