### ISSUE TITLE
Braille patterns have confusing spacing

### ISSUE THREAD

**Issue by dscorbett** [slavfox/Cozette#39]
The side bearings of the braille patterns are too small relative to the internal spacing between dots. For example, U+2831 is hard to distinguish from <U+2808, U+2806>. [Section 703.3.1 of the ADA Accessibility Standards](https://www.access-board.gov/ada/#ada-703_3_1) indicates the proper ratios.
![⠱⠈⠆](https://user-images.githubusercontent.com/1124347/102019371-2d78eb80-3d41-11eb-8c93-f9c4cb10997f.png)

**Comment by slavfox** [comment]
I've kept coming back to this over the years to try and figure out if this can or should be fixed, but ultimately could not find a way to. Braille characters in bitmap fonts are used pretty much exclusively for terminal drawing; the font itself is far from accessible, and braille characters are impossible to implement properly within its constraints.
