### ISSUE TITLE
Symbols for text based status bar 

### ISSUE THREAD

**Issue by stubbornGarrett** [slavfox/Cozette#4]
For text based status bars like i3bar, i3blocks, xmobar, dwm-bar, etc., it would be great to have some symbols to label displayed informations (temperature, volume, memory, ...).
Are there already plans to include such ones?

Below I listed some specific symbols, which I use or have used at some point, with the corresponding unicode of [font-awesome](https://fontawesome.com/cheatsheet) / [nerd-fonts](https://www.nerdfonts.com/cheat-sheet).

Volume
- volume-mute (f6a9 / fc5d)
- volume-off (f026 / f026)
- volume-down (f027 / f027)
- volume-up (f028 / f028)

Battery
- battery-full (f240 / f240)
- battery-three-quaters (f241 / f241)
- battery-half (f242 / f242)
- battery-quater (f243 / f243)
- battery-empty (f244 / f244)
- plug (f1e6 / f1e6)

Temperature (in my opinion, full, empty, ..., are not necessary)
- thermometer-half (f2c9 / f2c9)

Web browser (I saw that nf-dev-* is already on the roadmap, so most browser icons should be included there. The globe would be multifunctional)
- globe (f0ac / f0ac)

Network (\ue619 is already included but it got only 3/4 of height, which looks funny in my specific setup. One with a third "wave" would be nice or maybe a variation which is symmetrical, like the one below)
- wifi (f1eb / f1eb)
- ethernet (f796 / f6ff)

Workload
- chart-area (f1fe / f1fe)
- chart-bar (f080 / f080)
- memory (f538 / -)
- microchip (f2db / f2db)

Storage
- database (f1c0 / f1c0)
- hdd (f0a0 / f0a0)

Media
- headphones (f025 / f025/f7ca)
- headphones-slash (- /fccc)
- microphone (f130 / f130)
- microphone-slash (f131 / f131)
- eject (f052 / f052)

Other
- bell (f0f3 / f0f3)
- bell-slash (f1f6 / f1f6)
- calendar (f133 / f133)
- clock (f017 / f017)
- key (f084 / f084/f80a)

Weather (I don't use them but often see them in use on [r/unixporn](https://www.reddit.com/r/unixporn/))
e.g. cloud-sun (f6c4 / e21d)

I triple checked and hope, that I didn't list anything that's already included.

**Comment by slavfox** [comment]
Will do! Nerdfonts glyphs are a priority for inclusion (and so, all inclusion requests for them will get accepted and implemented), but there's *so many* of them that I wait for someone to request support for specific tools/glyphs before implementing them. 
This will go into the next release.

**Comment by slavfox** [comment]
These are now in the repo, I'll make a new release including these glyphs and the cyrillic block (#5) this weekend.
