### ISSUE TITLE
Add stressed greek characters

### ISSUE THREAD

**Issue by Vagos** [slavfox/Cozette#43]
Please include the remaining stressed greek characters such as έ, ί, ό, ύ, ή. 
Simply put, add a tone mark alternative above the already existing greek characters.

**Comment by dnnis** [comment]
Current Screen when these greek chars are inputted on the term:
![problem](https://user-images.githubusercontent.com/57800665/122830024-6dbcb600-d2f0-11eb-876d-9963d1d8a464.png)

**Comment by fluix-dev** [comment]
I think this should be closed, now that the PR was merged and released.
