### ISSUE TITLE
psf fonts?

### ISSUE THREAD

**Issue by goolord** [slavfox/Cozette#47]
i want to use cozette for my console, especially large sizes since my eyesight is poor

**Comment by slavfox** [comment]
Consider using [bdf2psf](https://aur.archlinux.org/packages/bdf2psf/). I haven't tried it myself, so I can't vouch for whether it'll work or not.

**Comment by goolord** [comment]
i tried it, it does work but i couldn't figure out how to configure the size

**Comment by slavfox** [comment]
Bitmap fonts are designed and drawn at a specific size; Cozette is a 6x13px font and is stored as a series of 6x13px bitmaps. They don't scale the way vector fonts do; a quick google search found [bdfresize](https://aur.archlinux.org/packages/bdfresize/) - something like `bdfresize -f 2 cozette.bdf > cozette12px.bdf` should output a 2x upscaled file, which you should be able to convert to psf with `bdf2psf`.

**Comment by goolord** [comment]
ok, that should be good enough for my use, thanks so much for your help
