### ISSUE TITLE
Bring full cyrillic support

### ISSUE THREAD

**Issue by notpushkin** [slavfox/Cozette#5]
This is sooooo neat! I'm wondering, why are `абчё` the only supported Cyrillic letters and is there any chance to bring full support? I'm really new to pixel fonts (and fonts in general) but I could work on a PR if you told me where to start :)

**Comment by slavfox** [comment]
Yes, absolutely! The lack of Cyrillic is an omission, the rest of the glyphs will make it to the next release.

**Comment by slavfox** [comment]
With v.1.5.0, Cozette now has the entire Cyrillic and Cyrillic supplement block, sans the combining characters:

![image](https://user-images.githubusercontent.com/35173529/75044868-9c3f3c80-54c2-11ea-84e5-800d8fecbbfb.png)

I tried to make the glyphs readable, but I'm not familiar with Cyrillic, so please do try it out and reopen this issue if any glyphs are incorrect :sweat_smile:

**Comment by notpushkin** [comment]
Awesome work, thank you so much! A few things that bug me:

![before](https://user-images.githubusercontent.com/1298948/75052461-b6881300-54e0-11ea-90e4-941502adf89c.png)

- `Щщ` are 1 px shorter than others (I guess it's to compensate the width?)
- `Цц`'s bottom can be moved down a bit
- `г` looks just a bit too wide
- `ъ` is round and `ь` is sharp (doesn't look too bad but still caught my attention)

![after](https://user-images.githubusercontent.com/1298948/75052537-d4557800-54e0-11ea-86e8-ac15c8eed049.png)

- Bonus: if we can move `щ` so that it's, something like this can be done so that it doesn't stick to the previous letter:

![3](https://user-images.githubusercontent.com/1298948/75052582-e59e8480-54e0-11ea-88a8-9cd4a7b52391.png)

This interpretation is a bit more calligraph-ish, but still should be fairly readable:

![4](https://user-images.githubusercontent.com/1298948/75053368-395d9d80-54e2-11ea-8ef9-db388b9527b8.png)

What do you think?

**Comment by slavfox** [comment]
Thank you for taking your time to review this!
- `Щщ` were screwed up by accident. I've fixed them.
- `Цц` is a result of my ignorance of Cyrillic :sweat_smile: Fixed as well.
- `ъ` was round in an attempt to keep it visually distinct from `Ъ`. I'm debating between adding a bottom serif to `Ь`:
![image](https://user-images.githubusercontent.com/35173529/75058466-53e04880-54db-11ea-991f-de98c1968b58.png)
  or making `ь` round as well. Any preference?

**Comment by slavfox** [comment]
I've decided to go for a middle ground and keep the sharp corner on both of `ьъ`, and omit the serif - instead, ь is slightly narrower than Ь (which seems to match how both of them look in my browser). Could you download [v.1.5.1](https://github.com/slavfox/Cozette/releases/tag/v.1.5.1) and see if there's anything else that might need tweaking?

**Comment by notpushkin** [comment]
Sorry for the wait! Tried it over the weekend and it works quite nicely, except that `щ` is clipped in Konsole (still need to test in other terminal emulators):

![image](https://user-images.githubusercontent.com/1298948/75153185-cf303d00-571b-11ea-919b-0f2e3fe3c3a3.png)

Still, it looks readable (to me at least). Thank you again for your hard work!

**Comment by slavfox** [comment]
Huh, that's weird; it's technically an oversize glyph, so it's not entirely unexpected, but I haven't seen other terminal emulators cut the pixels outside the bounding box off. 
Here's how it looks in Alacritty:
![image](https://user-images.githubusercontent.com/35173529/75154694-989ff580-570e-11ea-81b8-e4a05559fa2d.png)
Note that the oversize pixels get drawn over by the cursor, but they're still there.

This way to draw the glyph probably wouldn't be correct, would it? It'd fix that problem:
![image](https://user-images.githubusercontent.com/35173529/75154788-d69d1980-570e-11ea-9a44-e15ccf5644d3.png)

**Comment by notpushkin** [comment]
I've thought about it too, but it's a bit weirder IMO. If the oversize variant renders OK in most apps, I'd rather go with it.

**Comment by slavfox** [comment]
:+1: 
Alright, closing this issue, then. Thank you so much for helping me out with this, it's pretty hard to guess how glyphs you can't read should look, so your help was invaluable!
