### ISSUE TITLE
Broken symbols uE796, uF121, uF462, uFABF

### ISSUE THREAD

**Issue by cpkio** [slavfox/Cozette#54]
I've found out build 1.10 has already been broken in this matter: those glyphs are rendered as dots or as blank space. It seems glyph going off-edge can break some renderings.

**Comment by cpkio** [comment]
Redesigned the glyph to work, but will see if you will invent a fix for a few extra pixels no to break a glyph.

**Comment by slavfox** [comment]
![image](https://user-images.githubusercontent.com/35173529/124224337-bef55280-db05-11eb-9710-5e1cf3647304.png)
These render fine for me under xterm, alacritty, and gedit. Where are they broken?

**Comment by cpkio** [comment]
In Windows none of glyphs mentioned show up as expected (in DP4 font viewer and ConEmu terminal I use). Probably the Windows renderers work differently? It can handle a 1-2 extra pixels off-grid, but not more.

v1.100 screenshot
![CozetteVector](https://user-images.githubusercontent.com/1917113/124226480-d9cdc400-db11-11eb-9459-716ae5ed57f2.png)

**Comment by cpkio** [comment]
And 1.112 is almost OK, only uF462 not showing… Dunno whats happening.
![CozetteVector2](https://user-images.githubusercontent.com/1917113/124227283-177f1c80-db13-11eb-9581-a3ebf4630f31.png)

**Comment by slavfox** [comment]
I think I know what's happening here. I've redrawn the other glyphs; it seems that if a glyph exceeds the left margin, Windows will display only the part before the margin.

This might be fixed in [v.1.11.3](https://github.com/slavfox/Cozette/releases/tag/v.1.11.3).

**Comment by slavfox** [comment]
Since there was no further conversation here and to my knowledge this should be resolved, I'm closing this issue. Feel free to reopen if it still occurs.
