### ISSUE TITLE
Inconsistent character widths in vector font

### ISSUE THREAD

**Issue by Haspaker** [slavfox/Cozette#55]
The vector version of the font, CozetteVector, does not appear to be entirely fixed width. Some characters, such as the pause symbol (U+F04C) and the circled plus symbol (U+F055) have a smaller width, leading to misalignment (as clearly seen in the last column of the image below).

<img width="239" alt="Misaligned" src="https://user-images.githubusercontent.com/1615613/129753272-157dba56-e0c5-4aab-8f02-93bfc827308f.png">

I don't know much about fonts or FontForge, but I noticed that all the offending characters declare an unusual `Width` in the Cozette.sfd file (945 instead of 1024).

```
StartChar: uniF04C
Encoding: 61516 61516 1123
Width: 945
Flags: W
LayerCount: 2
EndChar

StartChar: uniF055
Encoding: 61525 61525 1571
Width: 945
Flags: W
LayerCount: 2
EndChar
```
When I change the `Width` property to 1024 and rebuild, the characters become properly aligned:

<img width="215" alt="Aligned" src="https://user-images.githubusercontent.com/1615613/129754559-abc78cff-1cfa-4321-a7f3-def5a112314b.png">

Is there a good reason these characters declare a different width, or is simply an oversight? If it's an oversight I can submit a pull request to fix it.

**Comment by cpkio** [comment]
You didn't mention your OS and used software.

**Comment by Haspaker** [comment]
@cpkio macOS Catalina, system wide (any software).

**Comment by cpkio** [comment]
I think this happens in software not enforcing glyph grid (like my terminal emulator in Windows, ConEmu, does, so I dont see any problems). I've done the replacements, they seem to do some width difference in non-terminal software. My PR is still waiting for review, so make your PR after @slavfox will merge.

**Comment by cpkio** [comment]
@Haspaker You want *all* the `Width: 945` to be replaced by `Width: 1024`? I've done it in my fork already, will PR (with my other changes) if this is OK for you.

**Comment by Haspaker** [comment]
@cpkio I haven't done any more tests except with the two characters mentioned above, but my guess is that all widths should be set to 1024, since I have no reason to think these 2 characters are special in any way. If you want to PR that's OK with me!

**Comment by slavfox** [comment]
![image](https://github.com/slavfox/Cozette/assets/35173529/d5e50bc2-58a7-4093-b729-b4e0680de977)
I got a chance to debug a lot of CozetteVector issues today, as of 1.19.2-hidpi CozetteVector renders properly, closing.
