### ISSUE TITLE
Add svelte and gitignore icons

### ISSUE THREAD

**Issue by RaafatTurki** [slavfox/Cozette#64]
~~I don't even know how this is possible.~~

![image](https://user-images.githubusercontent.com/16624558/154593105-cc7f7f3a-42a0-4478-b5c7-a5df47868b41.png)
in particular the `svelte` and `.gitignore` icons as they're taking 2 columns

~~which makes me think they're not implemented in cozette and my terminal is pulling them from elsewhere.
if that's the case kindly reword this issue to a support request for the above 2 mentioned icons.~~

EDIT: see my comment below

**Comment by fluix-dev** [comment]
> which makes me think they're not implemented in cozette and my terminal is pulling them from elsewhere.

I believe this is the case. You can try looking for these symbols in https://github.com/slavfox/Cozette/blob/master/img/charmap.txt

**Comment by RaafatTurki** [comment]
indeed, they're both missing
`U+0F260` 
`U+0E702` 

**Comment by slavfox** [comment]
Done in v.1.14.0
