### ISSUE TITLE
Glyph to represent NixOS missing

### ISSUE THREAD

**Issue by oatmealine** [slavfox/Cozette#71]
I'm wondering if there's any chance a glyph could be added to represent [Nix](https://nixos.org/)'s logo. A simple snowflake could work, which could be any of these:

- ❄️ ['SNOWFLAKE' (U+2744)](https://www.fileformat.info/info/unicode/char/2744/index.htm)
- ❅ ['TIGHT TRIFOLIATE SNOWFLAKE' (U+2745)](https://www.fileformat.info/info/unicode/char/2745/index.htm)
- ❆ ['HEAVY CHEVRON SNOWFLAKE' (U+2746)](https://www.fileformat.info/info/unicode/char/2746/index.htm)

Or, as an alternative, the NixOS logo from [Nerd Fonts](https://www.nerdfonts.com/), specifically [font-logos](https://github.com/lukas-w/font-logos) (`fl-nixos`). I'd highly appreciate it!

**Comment by slavfox** [comment]
U+F313 (fl-nixos) already exists in cozette and is a text form of the NixOS logo. I added U+2744 in v.1.14.0.

**Comment by oatmealine** [comment]
Huh - I'm not sure why I couldn't see either when typing them out in a text editor, thanks!
