### ISSUE TITLE
[Asking] What different between CozetteVector.dfont and CozetteVector.otf.dfont

### ISSUE THREAD

**Issue by haunt98** [slavfox/Cozette#74]
I can use CozetteVector.dfont on macOS but can not CozetteVector.otf.dfont

**Comment by slavfox** [comment]
They're just different formats exported from FontForge. I offer most of the formats that FontForge can export, but have no idea if they work or not - I can only guarantee that Cozette bitmap .otb works. `.otf.dfont` and `_bitmap.ttf` specifically should probably be considered non-useful and removed.

**Comment by haunt98** [comment]
Thanks for your explanation. It's clear now.
