### ISSUE TITLE
Popular prompt symbols

### ISSUE THREAD

**Issue by vaskark** [slavfox/Cozette#75]
276E and 276F would be really nice if they were closer to F053 and F054 (for shell prompts and the like). More distinctively trianglular.

Just a thought. Thanks so much for all your hard work.

P.S. I'm aware most prompts allow customization of symbols.

**Comment by slavfox** [comment]
I'll look into this tomorrow and compare across different fonts. I feel like there was a reason why those look so different (other than 276E/F being normal Unicode glyphs and F053/4 being Nerd Fonts/FontAwesome) but I don't remember it off the top of my head and I agree that having those be so different is weird. Thanks for the suggestion!

**Comment by vaskark** [comment]
Thanks so much for responding. I changed my starship character to F054 just to see how it would look:

https://i.imgur.com/jLtZ9yD.png

Pretty sharp :)

**Comment by slavfox** [comment]
Giving it further thought, I decided to leave these as-is. I prefer 276E in my own prompt, and in general with Cozette I try to have glyphs be as distinct as possible - NerdFonts have a lot of similar but slightly different symbols, and I'd like to, in that spirit, offer choice between different styles of a similar glyphs whenever possible. If there are some people who prefer 276E and some who prefer F053, then making them both look the same will always hurt one of those groups, while leaving them as-is gives the user free choice to pick whatever glyph they prefer.
