### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by DaitiDay** [slavfox/Cozette#76]
Just wanted to know how much till ligatures and bold characters are added. Really want to use the font but those feature are a must for me.

**Comment by slavfox** [comment]
Never. 

Ligatures are straight up not supported in bitmap fonts, and a bold version would not only require redrawing most of Cozette's characters - which is far too large a job for me - but also is just not possible for a significant number of the glyphs without exceeding Cozette's bounding box.
