### ISSUE TITLE
Newest additions are non-normal width

### ISSUE THREAD

**Issue by cpkio** [slavfox/Cozette#77]
These are at least double width, and do not display correctly in CozetteVector.ttf at least:
⛔ (U+26D4 NO ENTRY)
✨ (U+2728 SPARKLES)
❓ (U+2753 BLACK QUESTION MARK ORNAMENT)

I dont care about three-byte glyphs, they arent available in vector font anyway.

**Comment by slavfox** [comment]
I base character widths on Python's `unicodedata.east_asian_width`, which corresponds to how `xterm` and `alacritty` display them. These get rendered as double-width in terminals using the bitmap font, so they're drawn as double-width.
