### ISSUE TITLE
Ö has wrong size

### ISSUE THREAD

**Issue by Alphacat999** [slavfox/Cozette#78]
Hi! First I'd like to thank you for making this amazing font! <3

I found an issue: 
`Ä (U+00C4)` and `Ü (U+00DC)` have the correct size BUT `Ö (U+00D6)` doesn't. Both `O`s have the same size.

Font Version: CozetteVector.ttf 1.17.1
OS: Windows 10
![Screenshot 2022-09-01 120359](https://user-images.githubusercontent.com/73029710/187890324-140ab8bc-3b25-43fc-bb6a-8cfa945ed1c9.png)

**Comment by slavfox** [comment]
Ä and Ü had an incorrect size, they were too short; Ö was correct. I pushed an update that fixes umlauted capitals.

**Comment by Alphacat999** [comment]
Ah okay, I thought they were correct since letters like È are shorter too. :) Thanks for clarification.
