### ISSUE TITLE
Question about the 4

### ISSUE THREAD

**Issue by Alphacat999** [slavfox/Cozette#79]
I was wondering if the 4 is supposed to be one pixel wider than the other numbers (6 pixels while the others are 5) and connect to other characters?
![Screenshot 2022-09-01 182125](https://user-images.githubusercontent.com/73029710/187966073-829bfb52-97bf-4ca3-a1d1-94a4703077ea.png)

**Comment by slavfox** [comment]
Yes, narrowing the 4 to fit within the same bounding box makes it look smaller than the other digits:
![image](https://user-images.githubusercontent.com/35173529/188081763-5b0aee03-5644-46e5-bcb3-6a23e70bd445.png)

With the "tail" extending one pixel past the bounding box the digits feel more balanced:
![image](https://user-images.githubusercontent.com/35173529/188081801-f2bb3cd2-e5a7-4abf-9db3-d6fc1476551b.png)
