### ISSUE TITLE
Bluetooth Icon

### ISSUE THREAD

**Issue by vlfldr** [slavfox/Cozette#84]
Hi, I'd like to request a bluetooth icon. Tried my hand at it but it looks awful. Thanks :)

**Comment by slavfox** [comment]
v.1.18.1 includes:

-  (U+F293)
-  (U+F294)
-  (U+F5AE)
-  (U+F5AF)
-  (U+F5B0)
-  (U+F5B1)
-  (U+F5B2)

**Comment by vlfldr** [comment]
Those look incredible! Thanks so much
