### ISSUE TITLE
Automatic changelog generation

### ISSUE THREAD

**Issue by slavfox** [slavfox/Cozette#9]
I waste *a lot* of time adding new glyphs to the changelog. This became especially apparent when working on #7, which would probably be done by now if I hadn't been keeping track of the glyphs. The glyph changelist could be easily auto-generated, by reading the list from the last commit, and comparing it to the current version.

**Comment by tsujp** [comment]
I could do this for you, did you have a list of requirements you want for it and then I can begin working.
