### ISSUE TITLE
build.py doesn't generate new glyphs

### ISSUE THREAD

**Issue by klinegareth** [slavfox/Cozette#90]
Was working on adding "ᴥ", but when I run `build.py` the font generates normally but the new character is missing. Not super familiar with how FontForge works, so I might be missing something obvious! Any help would be much appreciated

**Comment by slavfox** [comment]
I need more info to be able to help you. Have you saved the character, does it have a width set, did you run `build.py fonts` specifically, how are you verifying that the character is missing?
