### ISSUE TITLE
Ligatures support

### ISSUE THREAD

**Issue by NTBBloodbath** [slavfox/Cozette#99]
Hey, first of all thank you for this amazing font. I never thought I'd be using a bitmap font before lol.

I wanted to know if it would be possible to add ligatures in some way, and if it's possible, I would like to help in the process. :)

Cheers!

**Comment by slavfox** [comment]
It's not. The only feasible way to have ligatures in a bitmap font is what [scientifica](https://github.com/nerdypepper/scientifica) or [creep](https://github.com/romeovs/creep/wiki/Haskell-syntax-sugar) do using Vim's `conceal` feature, which works only in Vim and only for specified programming languages.

If you happen to write a Vim conceal plugin for Cozette I will be happy to link to it from the README, but that's it as far as my options go. Bitmap fonts do not support ligatures.
